services:
  # ZPMeow Application
  zpmeow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zpmeow_app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - LOG_FORMAT=console
      - LOG_OUTPUT=stdout
      - DATABASE_URL=postgres://zpmeow:zpmeow123@postgres:5432/zpmeow?sslmode=disable
      - WA_LOG_LEVEL=INFO
      - GLOBAL_API_KEY=dev-api-key-12345
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    networks:
      - zpmeow_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  zpmeow_sessions:
    driver: local
  zpmeow_logs:
    driver: local

networks:
  zpmeow_network:
    driver: bridge
